feat: update libcgroup to 3.2.0-1

diff --git a/scripts/init.d/cgred.in b/scripts/init.d/cgred.in
--- a/scripts/init.d/cgred.in
+++ b/scripts/init.d/cgred.in
@@ -1,17 +1,11 @@
 #!/bin/bash
+# SPDX-License-Identifier: LGPL-2.1-only
 #
 # Start/Stop the CGroups Rules Engine Daemon
 #
 # Copyright Red Hat Inc. 2008
 #
 # Authors:	Steve Olivieri <sjo@redhat.com>
-# This program is free software; you can redistribute it and/or modify it
-# under the terms of version 2.1 of the GNU Lesser General Public License
-# as published by the Free Software Foundation.
-# 
-# This program is distributed in the hope that it would be useful, but
-# WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 #
 # cgred		CGroups Rules Engine Daemon
 # chkconfig:	- 14 86
@@ -25,35 +19,51 @@
 # Provides:		cgrulesengd
 # Required-Start:	$local_fs $syslog $cgconfig
 # Required-Stop:	$local_fs $syslog
-# Should-Start:		
-# Should-Stop:		
+# Should-Start:
+# Should-Stop:
 # Short-Description:	start and stop the cgroups rules engine daemon
 # Description:		CGroup Rules Engine is a tool for automatically using \
 #			cgroups to classify processes
 ### END INIT INFO
 
-prefix=@prefix@;exec_prefix=@exec_prefix@;sbindir=@sbindir@
+sbindir=@sbindir@
 CGRED_BIN=$sbindir/cgrulesengd
-CGRED_CONF=/etc/cgrules.conf
 
 # Sanity checks
-[ -x $CGRED_BIN ] || exit 1
+[[ -x $CGRED_BIN ]] || exit 1
 
-# Source function library & LSB routines
-. /etc/rc.d/init.d/functions
-. /lib/lsb/init-functions
+#
+# Source LSB routines
+#
+SYSLIBFILE=/lib/lsb/init-functions
+OLDSYSLIBFILE=/etc/init.d/functions
+if [[ -x  $SYSLIBFILE ]] ; then
+  # shellcheck disable=SC1090
+  source $SYSLIBFILE
+elif  [[ -x $OLDSYSLIBFILE ]] ; then
+  # shellcheck disable=SC1090
+  source $OLDSYSLIBFILE
+  log_warning_msg() ( warning "$@" ; printf "\n" 1>&2 ; )
+  log_failure_msg() ( failure "$@" ; printf "\n" 1>&2 ; )
+  log_success_msg() ( success "$@" ; printf "\n" 1>&2 ; )
+else
+  log_warning_msg() ( printf "warning:%s\n" "$@" 1>&2 ;)
+  log_failure_msg() ( printf "failure:%s\n" "$@" 1>&2 ;)
+  log_success_msg() ( printf "success:%s\n" "$@" 1>&2 ;)
+fi
 
 # Read in configuration options.
-if [ -f "/etc/sysconfig/cgred.conf" ] ; then
-	. /etc/sysconfig/cgred.conf
+if [[ -f "/etc/sysconfig/cgred.conf" ]] ; then
+	# shellcheck disable=SC1091
+	source /etc/sysconfig/cgred.conf
 	OPTIONS="$NODAEMON $LOG"
-	if [ -n "$LOG_FILE" ]; then
+	if [[ -n "$LOG_FILE" ]]; then
 		OPTIONS="$OPTIONS --logfile=$LOG_FILE"
 	fi
-	if [ -n "$SOCKET_USER" ]; then
+	if [[ -n "$SOCKET_USER" ]]; then
 		OPTIONS="$OPTIONS -u $SOCKET_USER"
 	fi
-	if [ -n "$SOCKET_GROUP" ]; then
+	if [[ -n "$SOCKET_GROUP" ]]; then
 		OPTIONS="$OPTIONS -g $SOCKET_GROUP"
 	fi
 else
@@ -69,12 +79,12 @@ pidfile=/var/run/cgred.pid
 start()
 {
 	echo -n $"Starting CGroup Rules Engine Daemon: "
-	if [ -f "$lockfile" ]; then
-		log_failure_msg "$servicename is already running with PID `cat ${pidfile}`"
+	if [[ -f "$lockfile" ]]; then
+		log_failure_msg "$servicename is already running with PID $(cat ${pidfile})"
 		return 0
 	fi
-	num=`grep "cgroup" /proc/mounts | awk '$3=="cgroup"' | wc -l`
-	if [ $num -eq 0 ]; then
+	num=$(grep "cgroup" /proc/mounts | awk '$3=="cgroup"' | wc -l)
+	if [[ "$num" -eq 0 ]]; then
 		echo
 		log_failure_msg $"Cannot find cgroups, is cgconfig service running?"
 		return 1
@@ -82,28 +92,27 @@ start()
 	daemon --check $servicename --pidfile $pidfile $CGRED_BIN $OPTIONS
 	retval=$?
 	echo
-	if [ $retval -ne 0 ]; then
+	if [[ $retval -ne 0 ]]; then
 		return 7
 	fi
-	touch "$lockfile"
-	if [ $? -ne 0 ]; then
+	if ! touch "$lockfile"; then
 		return 1
 	fi
-	echo "`pidof $processname`" > $pidfile
+	pidof "$processname" > $pidfile
 	return 0
 }
 
 stop()
 {
 	echo -n $"Stopping CGroup Rules Engine Daemon..."
-	if [ ! -f $pidfile ]; then
+	if [[ ! -f $pidfile ]]; then
 		log_success_msg
 		return 0
 	fi
 	killproc -p $pidfile -TERM "$processname"
 	retval=$?
 	echo
-	if [ $retval -ne 0 ]; then
+	if [[ $retval -ne 0 ]]; then
 		return 1
 	fi
 	rm -f "$lockfile" "$pidfile"
@@ -132,21 +141,21 @@ case "$1" in
 		RETVAL=$?
 		;;
 	condrestart)
-		if [ -f "$lockfile" ]; then
+		if [[ -f "$lockfile" ]]; then
 			stop
 			start
 			RETVAL=$?
 		fi
 		;;
 	reload|flash)
-		if [ -f "$lockfile" ]; then
+		if [[ -f "$lockfile" ]]; then
 			echo $"Reloading rules configuration..."
-			kill -s 12 `cat ${pidfile}`
+			kill -s 12 "$(cat ${pidfile})"
 			RETVAL=$?
-			if [ $RETVAL -eq 0 ] ; then
-				log_success_msg
+			if [[ $RETVAL -eq 0 ]] ; then
+				log_success_msg ""
 			else
-				log_failure_msg
+				log_failure_msg ""
 			fi
 		else
 			log_failure_msg "$servicename is not running."
